# Generated by Django 6.1.1 on 2026-09-15 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.date(2026, 9, 15)),
        ),
    ]
