# Generated by Django 6.1.1 on 2026-09-16 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
