# Generated by Django 6.1.1 on 2026-09-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
